### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by andress134** [mbcmkay/Tiktok-report-bot#1]
The bot not working .
Tiktok will dont remove the video !

Try improve it using multi thr and proxies
@mbcmkay

**Comment by mbcmkay** [comment]
Will look into adding multi-threading and using proxies would you like auto scrape that automatically gets proxies or use your own?

Also the bot doesn't guarantee being able to remove a video but their is a slight chance.

**Comment by andress134** [comment]
> Will look into adding multi-threading and using proxies would you like auto scrape that automatically gets proxies or use your own?
> 
> Also the bot doesn't guarantee being able to remove a video but there is a slight chance.

The bot require using proxies because it look received alot bad feedback from same IP
With proxies bot will working much better
also using multi thr  (1 proxy = 1 bad feedback sent)
like for every feedback sent to use other proxy
